interface ItemArea {
    links:{
        name:string
        // link:string
        subLink?:ItemArea[]
    }[]
}

declare interface IBug {
    id: number;
    module: string;
    platform: string;
    summary: string;
    rootCause?: string;
    reportedBy: string;
    assignedTo: string;
    status: string;
    defectCategory: string;
    severity: string;
    priority: string;
}

export const demoLink:ItemArea = {
    links:[
        {
            name:'anoop',
            subLink:[
                {
                    links:[
                        {
                            name:'developer'
                        },
                        {
                            name:'bugs'
                        },
                        {
                            name:'unit test'
                        },
                        {
                            name:'front end',
                            subLink:[
                                {
                                    links:[
                                        {
                                            name:'react'
                                        },
                                        {
                                            name:'Angular'
                                        },
                                        {
                                            name:'Vue'
                                        },
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}

export const BugsDataSource:IBug[] = [
    {
      "id": 1,
      "module": "Branch  Dashboard",
      "platform": "BackOffice",
      "summary": "System pop up \"Cannot Fetch Dashboard data ",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Le Anne",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 2,
      "module": "HQ  Branch Transaction",
      "platform": "BackOffice",
      "summary": "Unable to view Branch Transaction because system display pop up \" Cannot Fetch Dashboard data",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Le Anne",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 3,
      "module": "HQ  Branch Transaction",
      "platform": "BackOffice",
      "summary": "System unable to search for existing investor",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Le Anne",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 4,
      "module": "HQ  Branch Transaction",
      "platform": "BackOffice",
      "summary": "Unable to view order because system display pop up \" Cannot Fetch Dashboard data",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Le Anne",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 5,
      "module": "HQ  Branch Transaction",
      "platform": "BackOffice",
      "summary": "unable to Export List",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Dilip",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 6,
      "module": "HQ  Branch Transaction",
      "platform": "BackOffice",
      "summary": "Unable to Track order",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Le Anne",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 7,
      "module": "HQ  Branch Transaction",
      "platform": "BackOffice",
      "summary": "Unable to view transaction order record from inbox",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Le Anne",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 8,
      "module": "Dashboard",
      "platform": "Tablet",
      "summary": "Error 'Invalid parameters given' error encencounter",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Aldrin",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 9,
      "module": "Dashboard",
      "platform": "Tablet",
      "summary": "Error 'Unexpected error encountered. Please contact support' error encencounter",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Aldrin",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 10,
      "module": "Left Nav",
      "platform": "Tablet",
      "summary": "EDD and Inbox are switched",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Aldrin",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 11,
      "module": "Dashboard",
      "platform": "Tablet",
      "summary": "Create 3 orders in one application but in Transaction dashboard only showed 1 order",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Le Anne",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 12,
      "module": "HQ  Branch Transaction",
      "platform": "BackOffice",
      "summary": "Fail to view PDF document",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Bala",
      "status": "Rejected",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 13,
      "module": "HQ  Branch Transaction",
      "platform": "BackOffice",
      "summary": "Missing status under the status overview container on the Transaction screen",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Dilip",
      "status": "Rejected",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 14,
      "module": "Branch  Dashboard",
      "platform": "BackOffice",
      "summary": "Missing background for Adviser screen",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Dilip",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P4-Low"
    },
    {
      "id": 15,
      "module": "HQ  Branch Transaction",
      "platform": "BackOffice",
      "summary": "Once click the joint holder button it changes the name but not the details section.",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Dilip",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 16,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Incomplete Tab i/o Pending Tab",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Jeremy",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P3-Moderate"
    },
    {
      "id": 17,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Search bar keywords",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Jeremy",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 18,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Filter - Filter Investor by i/f Filter Cases by",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Jeremy",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 19,
      "module": "EDD",
      "platform": "BackOffice",
      "summary": "Cannot Fetch Case details\" BO-M4 Retrieval failed. error modal appears on viewing the case summary",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Massoud",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 20,
      "module": "EDD",
      "platform": "BackOffice",
      "summary": "Cannot download a closed report\" BO-M4 Retrieval failed. error modal appears on viewing the case summary",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Massoud",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 21,
      "module": "EPF",
      "platform": "BackOffice",
      "summary": "Hand icon missing on mouse hover the edit and view icon in the EPF tab and submit button is enabled on press of space in reject remarks",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Dilip",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 22,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Missing \" view\" function from the rejected table.",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Jeremy",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 23,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Missing \" view\" function from the Approved table.",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Jeremy",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 24,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Submitted tab for normal submitted status should have eye icon and submitted with physical doc with action 3 dot button",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Nithin",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 25,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Filter - Missing Risk Profile label",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Jeremy",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 26,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Investor list mobile no format",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 27,
      "module": "Branch  Dashboard",
      "platform": "BackOffice",
      "summary": "Error modal appears on transaction report download",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 28,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Filter the risk profile, and date range displayed in all high-risk lists with all date range",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 29,
      "module": "Branch  Dashboard",
      "platform": "BackOffice",
      "summary": "Cannot mark as Received\" error modal appears in the With Physical doc tab",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 30,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Not reset the search bar in Investor List after logout and re login",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Aldrin",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 31,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Sorting arrow in all the Investor name columns are not in order",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 32,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Sorting arrow in all the Risk category columns are not in order",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 33,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Processing Branch should be \"Designated KIB Branch\" for the Account Summary section",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Jeremy",
      "status": "Verified",
      "defectCategory": "Cosmetic",
      "severity": "3-Medium",
      "priority": "P4-Low"
    },
    {
      "id": 34,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Re-enter Password field was enabled even though the user has not entered the New Password.",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Jeremy",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 35,
      "module": "Branch  Dashboard",
      "platform": "BackOffice",
      "summary": "Orders submitted after cut-off on previous day did not get moved to daily tab after batch refresh",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Alison",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 36,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Sorting arrow in all the Mobile no. columns are not in order",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Nithin",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 37,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Incomplete tab total number should add from Pending, Reroute, and Submitted pills number.",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Nithin",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 38,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Investor's profile missing last updated date under the Mobile no and Email address",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Nithin",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 39,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Export Report drop down did not follow the figma design.\nhttps://www.figma.com/file/2Au6rG0QSbnnjWFFEDplRU/KIB-Ext---ETB-3.1?node-id=3451%3A78771",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Dilip",
      "status": "Verified",
      "defectCategory": "Cosmetic",
      "severity": "3-Medium",
      "priority": "P4-Low"
    },
    {
      "id": 40,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Highlighted sections are not in sync with figma design in the dashboard",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Dilip",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P4-Low"
    },
    {
      "id": 41,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "The toasts did not appear on the top right of the screen when user export report for PDF and csv.",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Dilip",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 42,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Order Number should be selected as default in the Track order search modal.Also \"Order Number\" label (highlighted) should be dynamic.\nDefault selection should happen on click of cancel",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Anoop",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 43,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Search button in the Track Order modal is enabled on hit of space button",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Anoop",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P4-Low"
    },
    {
      "id": 44,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Cannot Fetch Tracking data\" error modal appears on searching the Transaction Number from the Track Order search modal",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 45,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Highlighted sections are not in sync with figma design in the track order search results screen",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 46,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Column header sorting should be reset when focus is moved from the track order search result screen",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Dilip",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 47,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Cannot Fetch Dashboard data\" error modal appears when \"Total Investments\" column header in the submitted order screen is sorted",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P4-Low"
    },
    {
      "id": 48,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Highlighted sections are not in sync with figma design in the track order filter screen",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Anoop",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 49,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Pagination is disabled and not able to click the item and next page icon in the track order search screen with filter results",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Anoop",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 50,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Employment Information section display blank for minor joint accout holder.",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Dilip",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 51,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "No action is performed on click of the Cancel button in the submitted order and Orders screen filter section",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Dilip",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 52,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Few fields missing under Investment Summary for Order Details.",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Jeremy",
      "status": "Rejected",
      "defectCategory": "Cosmetic",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 53,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "UX/UI  for Profile screen did not sync with the Figma design",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Jeremy",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 54,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Highlighted sections are not in sync with figma design in the tracking tab within the order summary screen",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Massoud",
      "status": "Verified",
      "defectCategory": "Cosmetic",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 55,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Cannot Fetch Transaction Tracking\" error appears in the tracking tab when level filter(branch CE and CE HQ) with no data is selected",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Anoop",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 56,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Export Order Tracking Report did not sync with figma design.",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Bala",
      "status": "Open",
      "defectCategory": "Cosmetic",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 57,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Toast did not display on the right side of the screen once user click the download for the Order Tracking Report",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Jeremy",
      "status": "Rejected",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 58,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Selected filter data in the Track Order search screen gets changed after viewing the tracking tab data and click of back arrow from the tracking tab",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Anoop",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 59,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Unexpected error encountered. Please contact suport .\" display when user click The Tracking Status",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Massoud",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 60,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Unexpected error encountered. Please contact suport .\" display when user click  the view Details",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Massoud",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 61,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Pending Payment expand details for pending item is Proof of Payment (Normal order)",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 62,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Copywriting for Pending Initial Order",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 63,
      "module": "Acknowledgement",
      "platform": "Tablet",
      "summary": "Acknowledgement for PRS and PRS recurring is wrong\n22AA1555 - Normal order PRS but showed the recurring\n22AA155Z - Recurring order but no values (RM0.00)",
      "rootCause": "Logic Issue/Error",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 64,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Copywriting for Pending Doc & Payment",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 65,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Copywriting for Pending Doc - Capital letter for the first letter (Certificate of Loss of Nationality)",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 66,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Copywriting for Pending Physical Doc",
      "rootCause": "Missed Requirements",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "Ready to test",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 67,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Pending Physical Doc - Tap on NRIC button and error 'Order status does not require upload documents' encountered",
      "rootCause": "Logic Issue/Error",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 68,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Pending Physical Doc (Normal order) - No W8-BEN button",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 69,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "System not sync with Figma which is missing Order Types pill",
      "rootCause": "",
      "reportedBy": "Fatin",
      "assignedTo": "Dilip",
      "status": "Deferred",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 70,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Logout position not sync with Figma",
      "rootCause": "",
      "reportedBy": "Fatin",
      "assignedTo": "Dilip",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 71,
      "module": "Investor email verification",
      "platform": "Tablet",
      "summary": "Enter correct OTP but error Invalid OTP display for resend new OTP in Investor Email Verification",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 72,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "System not sync with Figma which is missing hyphen symbol in IC number",
      "rootCause": "Missed Requirements",
      "reportedBy": "Fatin",
      "assignedTo": "Bala",
      "status": "Ready to test",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 73,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Pending Physical Doc (Normal order) - No W9 Form button",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 74,
      "module": "Acknowledgement",
      "platform": "Tablet",
      "summary": "Acknowledgement for UT Recurring\n22AA1561Z - Recurring order but no values (RM0.00)",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 75,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Filter screen not sync in Figma",
      "rootCause": "",
      "reportedBy": "Fatin",
      "assignedTo": "Dilip",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 76,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Pending Physical Doc - Error 'Order status does not require payment' encountered when tap on DDA/PFX form button",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 77,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Transaction Summary for Transaction tab not sync in Figma",
      "rootCause": "",
      "reportedBy": "Fatin",
      "assignedTo": "Anoop",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 78,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Pending Physical Doc page\n1. Header ' Submit Physical Document'\n2. No Banner\n3. Continue button",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Nithin",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 79,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Track Order search did not render any result for order with \"Pending Approval\" status",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 80,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Pending Doc page\n1. Header copywriting\n2. Continue button",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Nithin",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 81,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Cannot Fetch Order Summary\" error modal appears on viewing the track order result with \"Pending Receive\" status",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 82,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Wrong options in Date dropdown list field by Filter",
      "rootCause": "",
      "reportedBy": "Fatin",
      "assignedTo": "Dilip",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 83,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Missing order number(22AA1568)",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 84,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Back arrow click in the Track Order search results screen always takes the user back to the daily tab",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Dilip",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 85,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Cannot Fetch Dashboard Data\" error modal appears on use the Filter button",
      "rootCause": "",
      "reportedBy": "Fatin",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 86,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Cannot Fetch Status Overview\" error modal appears on viewing transaction which have Pending Doc & Payment status",
      "rootCause": "",
      "reportedBy": "Fatin",
      "assignedTo": "Massoud",
      "status": "Fixed",
      "defectCategory": "Functionality",
      "severity": "1-Critical",
      "priority": "P2-High"
    },
    {
      "id": 87,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Submitted the order, page should redirect to Incomplete - Submitted tab",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Nithin",
      "status": "Deferred",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 88,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Upcoming status is not displayed in the tracking tab",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Massoud",
      "status": "Fix In Progress",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P2-High"
    },
    {
      "id": 89,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Missing sorting arrow for Product and Funding",
      "rootCause": "",
      "reportedBy": "Fatin",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 90,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Different font colour and missing ash background in Status column on filtering by Pending Physical Doc pill",
      "rootCause": "",
      "reportedBy": "Fatin",
      "assignedTo": "Dilip",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 91,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Physical Documents accordion not sync in Figma for Pending Physical Doc pill",
      "rootCause": "",
      "reportedBy": "Fatin",
      "assignedTo": "Massoud",
      "status": "Rejected",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 92,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Status History Tracking not sync in Figma",
      "rootCause": "",
      "reportedBy": "Fatin",
      "assignedTo": "Jan",
      "status": "Rejected",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 93,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Payment Summary not sync in Figma for Pending Initial Order pill",
      "rootCause": "",
      "reportedBy": "Fatin",
      "assignedTo": "Anoop",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 94,
      "module": "Branch  Dashboard",
      "platform": "BackOffice",
      "summary": "Old date in the new due date field is reset on click of cancel within the datepicker section in the Extend Due Date screen",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Dilip",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 95,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "BR-Rerouted status appears twice and no status is displayed in tracking tab after due date is extended",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Massoud",
      "status": "Rejected",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P2-High"
    },
    {
      "id": 96,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "NRIC for primary account holder is displayed as flase in the submitted order dashboard",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 97,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Cannot Fetch Dashboard Data\" error modal appears on sorting the list by Last Updated",
      "rootCause": "",
      "reportedBy": "Fatin",
      "assignedTo": "Dilip",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 98,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "IC number displayed as 'false'",
      "rootCause": "",
      "reportedBy": "Fatin",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 99,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Track Order search did not render any result for order with \"Void\" status and if track order using order number which have 'Z' (22AA0134Z) it not display the data",
      "rootCause": "",
      "reportedBy": "Fatin",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 100,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Track Order search by Investor Name did not render correct result",
      "rootCause": "",
      "reportedBy": "Fatin",
      "assignedTo": "Bala",
      "status": "Rejected",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 101,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Copywriting - Invalid Softcopy documents: i/o Invalid Documents:",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Nithin",
      "status": "Rejected",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 102,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Rerouted order - error 'Invalid parameter given'",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "Fix In Progress",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 103,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Incorrect Transaction Number and Transaction Type",
      "rootCause": "Logic Issue/Error",
      "reportedBy": "Fatin",
      "assignedTo": "Anoop",
      "status": "Ready to test",
      "defectCategory": "Database Error",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 104,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Back arrow click in the Track Order search results screen redirect to All pill Status",
      "rootCause": "",
      "reportedBy": "Fatin",
      "assignedTo": "Anoop",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 105,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Pending Physical Doc - Capital letter for W9 Form",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 106,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Error and app crashed when tap on W9 Form button",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Nithin",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 107,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "The PDF version for Transaction Tracking Report dont have footer.",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Bala",
      "status": "Open",
      "defectCategory": "Cosmetic",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 108,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Unable to view Pending Doc & Payment order.",
      "rootCause": "Logic Issue/Error",
      "reportedBy": "Felicia",
      "assignedTo": "Bala",
      "status": "Ready to test",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 109,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Pending status is not displayed in the tracking tab and submitted for adviser is displayed twice",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Massoud",
      "status": "Open",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 110,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Cannot Fetch Dashboard data\" error modal appears on selecting the filter options as \"All Categories\" and \"Branch Name\" in the Upcoming,Physical Doc, Rerouted and History tabs",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Dilip",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P2-High"
    },
    {
      "id": 111,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "After successfully download the Submission Summary Receipt the banner is still showing",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Nithin",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 112,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Missing CE(HQ) level filter and its details  in the tracking tab when a rejected order request is approved by a HQ CE Checker",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Massoud",
      "status": "New",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P2-High"
    },
    {
      "id": 113,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "All downloaded Submission Summary Receipt is showing the same order (22AA0138)",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "Open",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 114,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Status History Tracking level display 2 time \"All\" pill",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Dilip",
      "status": "Rejected",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 115,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "When tap on the other tab, the download action should be canceled",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Nithin",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 116,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Filters selected overlaps the \"Clear All\" link in the history tab",
      "rootCause": "Browser Support Issue",
      "reportedBy": "Murali",
      "assignedTo": "Dilip",
      "status": "Fix In Progress",
      "defectCategory": "Cosmetic",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 117,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Selected filters in the daily,upcoming,physical doc and history tabs are not reset when the focus is moved to other tabs in the dashboard",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Dilip",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P2-High"
    },
    {
      "id": 118,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "App crashed when tap on eye icon",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Nithin",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 119,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Background colour for upcoming status in tracking tab is not in sync with figma",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Anoop",
      "status": "Verified",
      "defectCategory": "Cosmetic",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 120,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "After tap on Submission Summary Receipt button, the list only show the submitted with physical doc but after view the order details, the list show all the submitted orders",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Nithin",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 121,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Orders rerouted and submitted after cut-off on previous day still available in the upcoming tab but the with current status as Pending",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Massoud",
      "status": "New",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 122,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Error modal appears when viewing the request for approval from inbox notification by a branch ce checker",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Dilip",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 123,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "App crashed when tap on Pending Initial Order eye icon",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Nithin",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 124,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Incorrect transaction Number in the transaction tab within order summary for pending receive status order",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Anoop",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P3-Moderate"
    },
    {
      "id": 125,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Last selected tab in dashboard remains in focus on click of submitted in the side navigation menu",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Dilip",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P3-Moderate"
    },
    {
      "id": 126,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Data in the search field remains when focus is moved out from dashboard and returned back",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Dilip",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 127,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Track Order by Account Number, Adviser Code and Transaction Number are not render result",
      "rootCause": "Logic Issue/Error",
      "reportedBy": "Fatin",
      "assignedTo": "Bala",
      "status": "Ready to test",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 128,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Submitted and Pending Submission menu under the Transactions in side navigation menu is not highlighted when focus is moved out from dashboard to track order search or order summary screens",
      "rootCause": "Routing Issue",
      "reportedBy": "Murali",
      "assignedTo": "Dilip",
      "status": "Open",
      "defectCategory": "Cosmetic",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 129,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Pending status is not displayed in the tracking tab for an In review status order",
      "rootCause": "",
      "reportedBy": "Murali",
      "assignedTo": "Massoud",
      "status": "Open",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P2-High"
    },
    {
      "id": 130,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Incorrect behaviour for Status pill after reset the filter details",
      "rootCause": "",
      "reportedBy": "Fatin",
      "assignedTo": "Anoop",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P2-High"
    },
    {
      "id": 131,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Incorrect behaviour for Status pill when clicking \"Clear All\" link",
      "rootCause": "",
      "reportedBy": "Fatin",
      "assignedTo": "Anoop",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P2-High"
    },
    {
      "id": 132,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Missing Account Summary accordion in the Transaction tab for Pending Submission Order",
      "rootCause": "Missed Requirements",
      "reportedBy": "Fatin",
      "assignedTo": "Anoop",
      "status": "Ready to test",
      "defectCategory": "Missing Design",
      "severity": "3-Medium",
      "priority": "P2-High"
    },
    {
      "id": 133,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Missing amount in Payment Summary for order with recurring",
      "rootCause": "",
      "reportedBy": "Fatin",
      "assignedTo": "Massoud",
      "status": "Fix In Progress",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P2-High"
    },
    {
      "id": 134,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Copywriting - Voided reason",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "Open",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 135,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "All filter tags are displayed even when only 2 results matched the selected filter tags",
      "rootCause": "Logic Issue/Error",
      "reportedBy": "Murali",
      "assignedTo": "Anoop",
      "status": "Ready to test",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 136,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "City / Town\" label did not sync with figma",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Jeremy",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 137,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "The Update Password button should be disabled if the error message still showing below the New Password Field",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Jeremy",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 138,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "W9 form only requires uploading one time per application",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "Fix In Progress",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 138,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Tapped on the Certificate of Loss of Nationality button and brings it to the Upload Proof of Payment page",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Nithin",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 139,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "EDD Overdue 2 Copywriting",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "New",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 140,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "All CE HQ user not able to login the system",
      "rootCause": "",
      "reportedBy": "Fatin",
      "assignedTo": "Bala",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "1-Critical",
      "priority": "P1-Intermediate"
    },
    {
      "id": 141,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Filter pill and Clear All link dissapear but the table still remain filtered after click Back Arrow from Order Summary screen",
      "rootCause": "Logic Issue/Error",
      "reportedBy": "Fatin",
      "assignedTo": "Dilip",
      "status": "Fixed",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 142,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "the error message goes away during onBlur, even though the condition for error message to go away is “onChangeText”.",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Jeremy",
      "status": "Ready to test",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P2-High"
    },
    {
      "id": 143,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "EDD rerouted case status is Rerouted i/o Pending",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "New",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 144,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Income Distribution should be Mode of Income Distribution",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Jeremy",
      "status": "Ready to test",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 145,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Only one Level pill is available but system allow it to be click",
      "rootCause": "New Requirements",
      "reportedBy": "Fatin",
      "assignedTo": "Anoop",
      "status": "Ready to test",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 146,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "EDD History Tab for Completed status's expand icon",
      "rootCause": "Missed Requirements",
      "reportedBy": "Ema",
      "assignedTo": "Nithin",
      "status": "Verified",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 147,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Can't tap on the Completed status's expand icon",
      "rootCause": "Missed Requirements",
      "reportedBy": "Ema",
      "assignedTo": "Nithin",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 148,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "App crashed after tap on Cancelled status's expand icon",
      "rootCause": "Logic Issue/Error",
      "reportedBy": "Ema",
      "assignedTo": "Nithin",
      "status": "Verified",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 149,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Error 'Client not found' encountered when viewed EDD Profile",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "New",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 150,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Cannot Fetch Transaction Tracking\" error appears upon click Tracking tab for Pending Doc & Payment order",
      "rootCause": "",
      "reportedBy": "Fatin",
      "assignedTo": "Bala",
      "status": "New",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 151,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "EDD Rerouted case status's copywriting for Overdue 1 and Overdue 2",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "New",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 152,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Authorised Signatory blank",
      "rootCause": "",
      "reportedBy": "Felicia",
      "assignedTo": "Massoud",
      "status": "New",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 153,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Dashboard screen for CE HQ user not sync with Figma",
      "rootCause": "",
      "reportedBy": "Fatin",
      "assignedTo": "Anoop",
      "status": "Ready to test",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 154,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Counting for the pill Pending Submission Order not same from Dashboard and Branch Transactions",
      "rootCause": "",
      "reportedBy": "Fatin",
      "assignedTo": "Bala",
      "status": "New",
      "defectCategory": "Database Error",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 155,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Incorrect placeholder in search field for Physical Doc tab",
      "rootCause": "Logic Issue/Error",
      "reportedBy": "Murali",
      "assignedTo": "Dilip",
      "status": "Fixed",
      "defectCategory": "Cosmetic",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 156,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Missing font and background colour for the Status Pending Doc order",
      "rootCause": "Missed Requirements",
      "reportedBy": "Fatin",
      "assignedTo": "Dilip",
      "status": "Fixed",
      "defectCategory": "User Interface",
      "severity": "4-Low",
      "priority": "P4-Low"
    },
    {
      "id": 157,
      "module": "3.1",
      "platform": "BackOffice",
      "summary": "Profile tab under order summary is not in sync with the figma.Headers and arrangement of sections are not in sync",
      "rootCause": "Missed Requirements",
      "reportedBy": "Murali",
      "assignedTo": "Anoop",
      "status": "Fix In Progress",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 158,
      "module": "POP",
      "platform": "Tablet",
      "summary": "Cant submit the Orders in Onboarding. Error 'Invalid parameters given' encaountered",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "New",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    },
    {
      "id": 159,
      "module": "3.1",
      "platform": "Tablet",
      "summary": "Missing Canceled EDD remarks",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "New",
      "defectCategory": "User Interface",
      "severity": "3-Medium",
      "priority": "P3-Moderate"
    },
    {
      "id": 160,
      "module": "Acknowledgement",
      "platform": "Tablet",
      "summary": "Acknowledgement Signatures summary receipts \n1. Showed EPF for UT Cash & recurring order\n2. Showed undefined for recirring order",
      "rootCause": "",
      "reportedBy": "Ema",
      "assignedTo": "Bala",
      "status": "New",
      "defectCategory": "Functionality",
      "severity": "2-High",
      "priority": "P2-High"
    }
  ]