interface ItemArea {
    links:{
        name:string
        // link:string
        subLink?:ItemArea[]
    }[]
}

declare interface IBug {
    id: number;
    module: string;
    platform: string;
    rootCause?: string;
    reportedBy: string;
    assignedTo: string;
    status: string;
    defectCategory: string;
    severity: string;
    priority: string;
}

export const demoLink:ItemArea = {
    links:[
        {
            name:'anoop',
            subLink:[
                {
                    links:[
                        {
                            name:'developer'
                        },
                        {
                            name:'bugs'
                        },
                        {
                            name:'unit test'
                        },
                        {
                            name:'front end',
                            subLink:[
                                {
                                    links:[
                                        {
                                            name:'react'
                                        },
                                        {
                                            name:'Angular'
                                        },
                                        {
                                            name:'Vue'
                                        },
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}

export const BugsDataSource:IBug[] = [
  {
    "id": 1,
    "module": "Branch  Dashboard",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Le Anne",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 2,
    "module": "HQ  Branch Transaction",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Le Anne",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 3,
    "module": "HQ  Branch Transaction",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Le Anne",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 4,
    "module": "HQ  Branch Transaction",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Le Anne",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 5,
    "module": "HQ  Branch Transaction",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Dilip",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 6,
    "module": "HQ  Branch Transaction",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Le Anne",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 7,
    "module": "HQ  Branch Transaction",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Le Anne",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 8,
    "module": "Dashboard",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Aldrin",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 9,
    "module": "Dashboard",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Aldrin",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 10,
    "module": "Left Nav",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Aldrin",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 11,
    "module": "Dashboard",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Le Anne",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 12,
    "module": "HQ  Branch Transaction",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Bala",
    "status": "Rejected",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 13,
    "module": "HQ  Branch Transaction",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Dilip",
    "status": "Rejected",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 14,
    "module": "Branch  Dashboard",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Dilip",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P4-Low"
  },
  {
    "id": 15,
    "module": "HQ  Branch Transaction",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Dilip",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 16,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Jeremy",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P3-Moderate"
  },
  {
    "id": 17,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Jeremy",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 18,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Jeremy",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 19,
    "module": "EDD",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Massoud",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 20,
    "module": "EDD",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Massoud",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 21,
    "module": "EPF",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Dilip",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 22,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Jeremy",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 23,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Jeremy",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 24,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Nithin",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 25,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Jeremy",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 26,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 27,
    "module": "Branch  Dashboard",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 28,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 29,
    "module": "Branch  Dashboard",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 30,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Aldrin",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 31,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 32,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 33,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Jeremy",
    "status": "Verified",
    "defectCategory": "Cosmetic",
    "severity": "3-Medium",
    "priority": "P4-Low"
  },
  {
    "id": 34,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Jeremy",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 35,
    "module": "Branch  Dashboard",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Alison",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 36,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Nithin",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 37,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Nithin",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 38,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Nithin",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 39,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Dilip",
    "status": "Verified",
    "defectCategory": "Cosmetic",
    "severity": "3-Medium",
    "priority": "P4-Low"
  },
  {
    "id": 40,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Dilip",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P4-Low"
  },
  {
    "id": 41,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Dilip",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 42,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Anoop",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 43,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Anoop",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P4-Low"
  },
  {
    "id": 44,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 45,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 46,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Dilip",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 47,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P4-Low"
  },
  {
    "id": 48,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Anoop",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 49,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Anoop",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 50,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Dilip",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 51,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Dilip",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 52,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Jeremy",
    "status": "Rejected",
    "defectCategory": "Cosmetic",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 53,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Jeremy",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 54,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Massoud",
    "status": "Verified",
    "defectCategory": "Cosmetic",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 55,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Anoop",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 56,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Bala",
    "status": "Open",
    "defectCategory": "Cosmetic",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 57,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Jeremy",
    "status": "Rejected",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 58,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Anoop",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 59,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Massoud",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 60,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Massoud",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 61,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 62,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 63,
    "module": "Acknowledgement",
    "platform": "Tablet",
    "rootCause": "Logic Issue/Error",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 64,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 65,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 66,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "Missed Requirements",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "Ready to test",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 67,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "Logic Issue/Error",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 68,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 69,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Fatin",
    "assignedTo": "Dilip",
    "status": "Deferred",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 70,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Fatin",
    "assignedTo": "Dilip",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 71,
    "module": "Investor email verification",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 72,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "Missed Requirements",
    "reportedBy": "Fatin",
    "assignedTo": "Bala",
    "status": "Ready to test",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 73,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 74,
    "module": "Acknowledgement",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 75,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Fatin",
    "assignedTo": "Dilip",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 76,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 77,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Fatin",
    "assignedTo": "Anoop",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 78,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Nithin",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 79,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 80,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Nithin",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 81,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 82,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Fatin",
    "assignedTo": "Dilip",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 83,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 84,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Dilip",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 85,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Fatin",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 86,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Fatin",
    "assignedTo": "Massoud",
    "status": "Fixed",
    "defectCategory": "Functionality",
    "severity": "1-Critical",
    "priority": "P2-High"
  },
  {
    "id": 87,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Nithin",
    "status": "Deferred",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 88,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Massoud",
    "status": "Fix In Progress",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P2-High"
  },
  {
    "id": 89,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Fatin",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 90,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Fatin",
    "assignedTo": "Dilip",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 91,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Fatin",
    "assignedTo": "Massoud",
    "status": "Rejected",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 92,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Fatin",
    "assignedTo": "Jan",
    "status": "Rejected",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 93,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Fatin",
    "assignedTo": "Anoop",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 94,
    "module": "Branch  Dashboard",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Dilip",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 95,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Massoud",
    "status": "Rejected",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P2-High"
  },
  {
    "id": 96,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 97,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Fatin",
    "assignedTo": "Dilip",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 98,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Fatin",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 99,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Fatin",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 100,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Fatin",
    "assignedTo": "Bala",
    "status": "Rejected",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 101,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Nithin",
    "status": "Rejected",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 102,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "Fix In Progress",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 103,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "Logic Issue/Error",
    "reportedBy": "Fatin",
    "assignedTo": "Anoop",
    "status": "Ready to test",
    "defectCategory": "Database Error",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 104,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Fatin",
    "assignedTo": "Anoop",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 105,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 106,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Nithin",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 107,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Bala",
    "status": "Open",
    "defectCategory": "Cosmetic",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 108,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "Logic Issue/Error",
    "reportedBy": "Felicia",
    "assignedTo": "Bala",
    "status": "Ready to test",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 109,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Massoud",
    "status": "Open",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 110,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Dilip",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P2-High"
  },
  {
    "id": 111,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Nithin",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 112,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Massoud",
    "status": "New",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P2-High"
  },
  {
    "id": 113,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "Open",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 114,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Dilip",
    "status": "Rejected",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 115,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Nithin",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 116,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "Browser Support Issue",
    "reportedBy": "Murali",
    "assignedTo": "Dilip",
    "status": "Fix In Progress",
    "defectCategory": "Cosmetic",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 117,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Dilip",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P2-High"
  },
  {
    "id": 118,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Nithin",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 119,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Anoop",
    "status": "Verified",
    "defectCategory": "Cosmetic",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 120,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Nithin",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 121,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Massoud",
    "status": "New",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 122,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Dilip",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 123,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Nithin",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 124,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Anoop",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P3-Moderate"
  },
  {
    "id": 125,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Dilip",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P3-Moderate"
  },
  {
    "id": 126,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Dilip",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 127,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "Logic Issue/Error",
    "reportedBy": "Fatin",
    "assignedTo": "Bala",
    "status": "Ready to test",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 128,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "Routing Issue",
    "reportedBy": "Murali",
    "assignedTo": "Dilip",
    "status": "Open",
    "defectCategory": "Cosmetic",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 129,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Murali",
    "assignedTo": "Massoud",
    "status": "Open",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P2-High"
  },
  {
    "id": 130,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Fatin",
    "assignedTo": "Anoop",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P2-High"
  },
  {
    "id": 131,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Fatin",
    "assignedTo": "Anoop",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P2-High"
  },
  {
    "id": 132,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "Missed Requirements",
    "reportedBy": "Fatin",
    "assignedTo": "Anoop",
    "status": "Ready to test",
    "defectCategory": "Missing Design",
    "severity": "3-Medium",
    "priority": "P2-High"
  },
  {
    "id": 133,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Fatin",
    "assignedTo": "Massoud",
    "status": "Fix In Progress",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P2-High"
  },
  {
    "id": 134,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "Open",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 135,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "Logic Issue/Error",
    "reportedBy": "Murali",
    "assignedTo": "Anoop",
    "status": "Ready to test",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 136,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Jeremy",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 137,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Jeremy",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 138,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "Fix In Progress",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 138,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Nithin",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 139,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "New",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 140,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Fatin",
    "assignedTo": "Bala",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "1-Critical",
    "priority": "P1-Intermediate"
  },
  {
    "id": 141,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "Logic Issue/Error",
    "reportedBy": "Fatin",
    "assignedTo": "Dilip",
    "status": "Fixed",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 142,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Jeremy",
    "status": "Ready to test",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P2-High"
  },
  {
    "id": 143,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "New",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 144,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Jeremy",
    "status": "Ready to test",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 145,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "New Requirements",
    "reportedBy": "Fatin",
    "assignedTo": "Anoop",
    "status": "Ready to test",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 146,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "Missed Requirements",
    "reportedBy": "Ema",
    "assignedTo": "Nithin",
    "status": "Verified",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 147,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "Missed Requirements",
    "reportedBy": "Ema",
    "assignedTo": "Nithin",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 148,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "Logic Issue/Error",
    "reportedBy": "Ema",
    "assignedTo": "Nithin",
    "status": "Verified",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 149,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "New",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 150,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Fatin",
    "assignedTo": "Bala",
    "status": "New",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 151,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "New",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 152,
    "module": "3.1",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Felicia",
    "assignedTo": "Massoud",
    "status": "New",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 153,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Fatin",
    "assignedTo": "Anoop",
    "status": "Ready to test",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 154,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "",
    "reportedBy": "Fatin",
    "assignedTo": "Bala",
    "status": "New",
    "defectCategory": "Database Error",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 155,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "Logic Issue/Error",
    "reportedBy": "Murali",
    "assignedTo": "Dilip",
    "status": "Fixed",
    "defectCategory": "Cosmetic",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 156,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "Missed Requirements",
    "reportedBy": "Fatin",
    "assignedTo": "Dilip",
    "status": "Fixed",
    "defectCategory": "User Interface",
    "severity": "4-Low",
    "priority": "P4-Low"
  },
  {
    "id": 157,
    "module": "3.1",
    "platform": "BackOffice",
    "rootCause": "Missed Requirements",
    "reportedBy": "Murali",
    "assignedTo": "Anoop",
    "status": "Fix In Progress",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 158,
    "module": "POP",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "New",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  },
  {
    "id": 159,
    "module": '3.1',
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "New",
    "defectCategory": "User Interface",
    "severity": "3-Medium",
    "priority": "P3-Moderate"
  },
  {
    "id": 160,
    "module": "Acknowledgement",
    "platform": "Tablet",
    "rootCause": "",
    "reportedBy": "Ema",
    "assignedTo": "Bala",
    "status": "New",
    "defectCategory": "Functionality",
    "severity": "2-High",
    "priority": "P2-High"
  }
]